### ISSUE TITLE
How to apply mask to existing text?

### ISSUE THREAD

**Issue by beltik** [RedMadRobot/input-mask-ios#22]
Hi,

What i i have define mask and delegate, and  want to set pre-defined tex to text field?

When i do - myTextField.txt = "12345678" mask is not applied.

**Comment by taflanidi** [comment]
Hi @beltik,
Thanks for your question.

In our README, there's a sample code in a [`Simple UITextField for the phone numbers`](https://github.com/RedMadRobot/input-mask-ios#simple-uitextfield-for-the-phone-numbers) paragraph:

```swift
class ViewController: UIViewController, MaskedTextFieldDelegateListener {
    
    var maskedDelegate: MaskedTextFieldDelegate!

    @IBOutlet weak var field: UITextField!
    
    open override func viewDidLoad() {
        maskedDelegate = MaskedTextFieldDelegate(format: "{+7} ([000]) [000] [00] [00]")
        maskedDelegate.listener = self

        field.delegate = maskedDelegate

        maskedDelegate.put(text: "+7 123", into: field)
    }
    
    open func textField(
        _ textField: UITextField, 
        didFillMandatoryCharacters complete: Bool,
        didExtractValue value: String
    ) {
        print(value)
    }
    
}
```

The line you might consider using in order to put some predefined text into the field is
```swift
maskedDelegate.put(text: "+7 123", into: field)
```
— broadly speaking, this method uses the same `Mask` instance as if it was a typical user typing, but passes the text programmatically.

**Comment by beltik** [comment]
Thanks, task may be closed. It worked.
