### ISSUE TITLE
menuController "Cut" not work

### ISSUE THREAD

**Issue by goodarmen96** [RedMadRobot/input-mask-ios#28]
I use MaskedTextFieldDelegate and assign it to textFiled (instance of UITextFiled) delegate property. After that, the "Cut" item of menuController not work, text disappear but it not saved in UIPasteboard. Other items like "Copy", "Paste" works correct

**Comment by taflanidi** [comment]
Hi @goodarmen96!
I'm a little bit familiar with your bug, and I'm 70% certain our library is not a root cause of it. 

I've noticed similar behavior in system apps on my iPhone for several times, yet I didn't find the exact reason. There is a couple of reports [circling](https://stackoverflow.com/questions/41196938/uitextfield-cut-does-not-fill-pasteboard) [around](https://stackoverflow.com/questions/36222980/uitextfield-in-uitableviewcell-breaks-cut-copy-paste-options) Stack Overflow here and there mentioning the weird "Cut" function behaviour.

My guess is, this has something to do with the universal handoff pasteboard, as this defect began to occur on my device since this feature was introduced, but I'm not 100% sure.

Nevertheless, it would be great if you could share some kind of a minimalistic project with me, where this issue typically occurs for you. Just in case I'm missing something.

**Comment by goodarmen96** [comment]
Test project
[inputMaskTst.zip](https://github.com/RedMadRobot/input-mask-ios/files/1871160/inputMaskTst.zip)

**Comment by taflanidi** [comment]
@goodarmen96,
Okay, got it. 
I'll look into it a little bit later today.

**Comment by taflanidi** [comment]
@goodarmen96,
Well, I've got good news and bad news.

Good news are: we've got potential ways of solving this problem. 
iOS hardwires `UIMenuController`'s cut action to the `UITextFieldDelegate`'s `textField(_:shouldChangeCharactersIn:replacementString:)` return value. This means "Cut" behaviour actually depends on the ability to edit the text.

Bad news are: there's no cheap & straightforward solution.
Our library heavily depends on that `false`; it would require us to rewrite a lot of logic in order to return `true` from `textField(_:shouldChangeCharactersIn:replacementString:)`. Moreover, there's no guarantee this will actually work.

Essentially, there's no distinct way to differentiate "Cut selection" and "Delete selection" actions on the `UITextFieldDelegate` side. However, you may consider using a workaround, which will require you to subclass `UITextField` and to patch its `cut(sender:)` method like this:

```swift
class UITextFieldMonkeyPatch: UITextField {
    override func cut(_ sender: Any?) {
        copy(sender)
        super.cut(sender)
    }
}
```

From our library perspective, this looks like an invasive solution. Thus, in the long term, I'm going to investigate "costly" `textField(_:shouldChangeCharactersIn:replacementString:)` method rewriting to bring the behaviour that would match the iOS SDK logic. Yet, here "long term" means months.

Hope, this helps.

**Comment by goodarmen96** [comment]
thanks, your monkey path method works
