### ISSUE TITLE
Blank space issues

### ISSUE THREAD

**Issue by caioremedio** [RedMadRobot/input-mask-ios#36]
I'm facing two issues regarding blank space.

1. I have this mask for credit card: `"[0000] [0000] [0000] [0000] [999]"` but the main problem is when user finishes typing mandatory numbers, it still says is not completed because the user didn't type the blank space before `[999]`. How can I fix this issue?

2. I have this mask for name input: `[A…]` but it doesn't allow me to input blank space, and it seems there is no symbol for that. I even tried to create my custom notation for blank space but no success. How can I allow at least one letter and optional blank spaces?

Thanks for this awesome library!

**Comment by taflanidi** [comment]
Hey @caioremedio!
Thanks for your questions. I already see a potential feature request.

**First**, for your `"[0000] [0000] [0000] [0000] [999]"` credit card mask custom notations might be your answer. You need an optional space character, like this:

`"[0000] [0000] [0000] [0000][s][999]"`

`Notation(character: "s", characterSet: CharacterSet(charactersIn: " "), isOptional: true)`

—please try it out and let me know your results.

**Second**, I noticed a logic flaw in our [`Compiler`](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/Helper/Compiler.swift#L288). Right now, our library tries to inherit characteristics of the `[…]` depending on the previous character, and it **doesn't support custom notations** for this previous character (see the link).

I'll need to update the library for your needs, okay?

**Comment by caioremedio** [comment]
Hi @taflanidi , thanks for quick reply.

**First:** I tried with `[s]` but it's not auto inserting blank space character. I'm missing something here?

I'm using subclass of `MaskedTextFieldDelegate`, I created some custom inits for `customNotations`:

```swift
class NotifyingMaskedTextFieldDelegate: MaskedTextFieldDelegate {

    weak var editingListener: NotifyingMaskedTextFieldDelegateListener?

    override init(format: String) {
        super.init(format: format)
    }

    convenience init(format: String, customNotations: [Notation]) {
        self.init(format: format)
        self.customNotations = customNotations
    }

    convenience init(format: String, customNotation: Notation) {
        self.init(format: format, customNotations: [customNotation])
    }
}
```

Initializing:

```swift
NotifyingMaskedTextFieldDelegate(
    format: "[0000] [0000] [0000] [0000][s][999]",
    customNotation: Notation(character: "s",
                             characterSet: CharacterSet(charactersIn: " "),
                             isOptional: true))
```

**Second:** Alright, but it's possible to include only blank space in the Compiler (along with Numbers and Letters)?

Thanks for the support.

**Comment by taflanidi** [comment]
Hey @caioremedio,

> I tried with [s] but it's not auto inserting blank space character. I'm missing something here?

Oh, I forgot about that. I even mentioned it at the end of [Custom notations](https://github.com/RedMadRobot/input-mask-ios#custom-notations) readme section. 

> I'm using subclass of MaskedTextFieldDelegate, I created some custom inits for customNotations

You don't need to subclass, actually. `MaskedTextFieldDelegate` [has](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift#L46) a corresponding public variable `customNotations`, and you just assign your list of notations to it.

Also, now I see with this approach you'll gain another problem with your extracted value. To be specific, this problem: `1234123412341234 999` — an unnecessary space.

BUT there exists an another approach you may incorporate to define the value is complete. `Mask` instances and the wrapper `MaskedTextFieldDelegate` provide a series of calculated metrics for the text and for the extracted value, like [`acceptableTextLength`](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/Mask.swift#L177), [`totalTextLength`](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/Mask.swift#L186), etc.

[MaskedTextFieldDelegate.acceptableValueLength()](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift#L150) will return `16` in your case, so you could compare the length of the extracted value to it in order to define typing is completed. 

2. 
> Alright, but it's possible to include only blank space in the Compiler (along with Numbers and Letters)?

In order to define behavior, `Compiler` needs to know the nature of ellipsis preceding character:
```
[A…]
 ^ this one defines, what symbols are accepted
```

For now, `Compiler` is limited to the basic set of `A a 0 9 - _`. Custom notations doesn't work when it comes to elliptical masks, this is a feature to be implemented.

**Comment by caioremedio** [comment]
>Oh, I forgot about that. I even mentioned it at the end of Custom notations readme section.

Oh my bad, didn't notice that.

>You don't need to subclass, actually. MaskedTextFieldDelegate has a corresponding public variable customNotations, and you just assign your list of notations to it.

No, i'm not subclassing just for custom notation, I'm using for other approaches (overriding `UITextField` methods). I've just comment that because I thought auto-completion not working was a bug, so I just wrote everything I was doing.

>MaskedTextFieldDelegate.acceptableValueLength() will return 16 in your case, so you could compare the length of the extracted value to it in order to define typing is completed.

Awesome, worked like a charm. So instead checking if `completed == true`, now I should rely on `value.count > MaskedTextFieldDelegate.acceptableValueLength()` right? I tested here and seems to work on all cases.

>Custom notations do not work when it comes to elliptical masks, this is a feature to be implemented.
Gotcha. In the meantime gonna use default `UITextFieldDelegate` for that.

Thanks again!

**Comment by taflanidi** [comment]
@caioremedio,

> Awesome, worked like a charm. So instead checking if completed == true, now I should rely on value.count > MaskedTextFieldDelegate.acceptableValueLength() right? 

Yep.

> Oh what I mean was, instead of implementing custom notations (if takes too much work) with ellipsis, just implement blank space character.

In fact, using of custom notations here would require less work.

> Gotcha. In the meantime gonna use default UITextFieldDelegate for that.

Stay tuned for the `Compiler` updates this weekend.

**Comment by taflanidi** [comment]
@caioremedio,

Alright, now elliptical masks support custom notations, too.

Check out the newest `3.4.1`.
