### ISSUE TITLE
Strong reference

### ISSUE THREAD

**Issue by MrJox** [RedMadRobot/input-mask-ios#50]
Is there a way for InputMask to work as a weak reference? Because when I pop my viewController it causes memory leak due to the strong reference. But if I set it to weak reference, mask isn't applied

**Comment by taflanidi** [comment]
Hey @MrJox,
Thanks for your question.

I'm afraid you've got to read about memory management in iOS apps more carefully, as our library's current implementation cannot cause memory leaks as there're no retain circles.

It's something inside your own project you've got to fix in order to solve this problem.

**Comment by DamascenoRafael** [comment]
**I do not think there is any memory leak**. But it would be interesting to be able to use the MaskedTextFieldDelegate as `weak` since it is recommended and accused by some linters.

As an example, I use SwiftLint and by default it has a [weak_delegate](https://github.com/realm/SwiftLint/blob/master/Rules.md#weak-delegate) rule saying 'Delegates should be weak to avoid reference cycles.'

Sorry for commenting on a closed issue, I can open a new one with this proposal if it is the best procedure.

**Comment by taflanidi** [comment]
@DamascenoRafael, you are basically asking for impossible, and here's why.

ARC requires at least one outgoing strong reference for each object to exist. If there are no strong references keeping your object alive — the object is deallocated. 

Here is an UML illustration for a common strong reference chain in your app:

![referencechain001](https://user-images.githubusercontent.com/6849363/46325728-5ac69c80-c602-11e8-990d-f3a1bbe65b78.png)

In this case a `UIViewController` instance plays the role of the `UITextView` listener — or so called "delegate". 

And by the SDK design, this circuit should never become a closed strong circuit, or a "retain circle":

![referencechain002](https://user-images.githubusercontent.com/6849363/46325816-c7da3200-c602-11e8-8285-d74104bec15a.png)

In order to ensure this, `UITextView.delegate` property is a `weak` property.

The same rule is applied to e.g. the `UITableViewController`, where a `UIViewController` contains a `UITableView`, which has a `weak` reference to its parent `UIViewController` playing a `UITableViewDataSource` & `UITableViewDelegate` at the same time.

![referencechain003](https://user-images.githubusercontent.com/6849363/46325993-7d0cea00-c603-11e8-9857-670009992490.png)

Now imagine you want to keep your source code clean and [SOLID](https://en.wikipedia.org/wiki/SOLID), so you make a separate object to play the role of the `UITableView` data source:

![referencechain004](https://user-images.githubusercontent.com/6849363/46326116-002e4000-c604-11e8-82da-d23cfc4200fd.png)

Now the question is: how do you keep your `MyDataSource` instance alive? There are no strong references leading to this object right now, so it is going to be deallocated right away.

The only way is to keep it attached somewhere, e.g.:

![referencechain005](https://user-images.githubusercontent.com/6849363/46326241-8d719480-c604-11e8-914d-c53fb91273f4.png)

— and THIS is going to be a **strong** reference. Your `UIViewController` instance is going to have a strong reference to your `MyDataSource` object.

### And now you basically want me to do this:

![referencechain006](https://user-images.githubusercontent.com/6849363/46326363-083aaf80-c605-11e8-9719-94f1bc8ab9fb.png)

— which is plain stupid and ain't gonna work under any circumstances, I'm sorry.

And again, excuse me, but you've got to learn how to use your tools and linters correctly *before* actually using them. Otherwise you'll receive all kinds of warnings without any clue of how to properly treat them.

**Comment by MrJox** [comment]
I was only saying the strong reference keeps my piped view controller alive for some reason so I have to set masked delegate to nil when I leave the controller. But thanks for the reply, that's much appreciated

**Comment by taflanidi** [comment]
@MrJox, I've thrown together a quick project [here](https://github.com/taflanidi/InputMaskMemoryLeakStudy).

There is a `UINavigationController` with two basic `UIViewController`s.

`ViewController2` contains a strong property for the text field delegate and a weak `IBOutlet`. The delegate itself contains an overridden `deinit` method with a single logger call. When this second view controller is popped, you receive a logger call. This basically means the `textFieldDelegate` and the `ViewController2` instances are deallocated. No need to set anything to `nil` whatsoever.

Your project definitely contains a more fundamental issue.
