### ISSUE TITLE
iOS 12 allows for a phone number paste option

### ISSUE THREAD

**Issue by patthehuman** [RedMadRobot/input-mask-ios#54]
How can I work with this repo with ios 12 paste phone number from auto complete?

**Comment by taflanidi** [comment]
Hey @patthehuman!
Thanks for your question.

Could you please be more specific about the scenario you are having trouble with?

**Comment by patthehuman** [comment]
Hello @taflanidi 

How are u this fine morning? Great to here from u!

We are usang the new item feature found in iOS12 where u can paste ur phone number directly from the keyboard.

In the examples, there isnt no support for pasting phone number and supporting the mask. Can u help us out?

**Comment by LinusGeffarth** [comment]
Guess you're talking about suggestions based on `textField.contentType` which you've set to phone number?

**Comment by taflanidi** [comment]
Hey @patthehuman!
I'm not sure what exactly you are talking about, but I assume @LinusGeffarth had guessed right, and you are having trouble with the suggestions based on the `contentType`.

Unfortunately, there's no simple way for our library to support these automatic suggestions.

The library heavily relies on this [`false`](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift#L183) right here, returned from the `textField(shouldChangeCharactersInRange:replacementString:)` call, which prevents pasting suggested text. 

From what I've found, suggested phones pasting is a two-step process. There are to separate consecutive calls. First, the contents of the `UITextField` are replaced with a single space `" "` string. Then this single space is replaced with the expected phone number.

In case when your `UITextField` denies the first step, second step doesn't occur at all, which is our problem. We can't say whether this first step is simply user trying to fill the field with garbage or whether it's the system's try to put suggested phone number.

For some reason system's keyboard can't replace the whole text with suggested phone number at once. 

I don't want to put an unreliable hardcode into the sources just because nobody at iOS SDK development team thought it might be a good idea to put some nice callbacks on events such as inserting autotext.

Please let me know, if this answers your question.

**Comment by LinusGeffarth** [comment]
When the `" "` is passed, we could hard-codedly check for that and then trim the text's whitespaces and still return true.
Right?

**Comment by taflanidi** [comment]
@LinusGeffarth, sure, but that's a completely arbitrary solution since there's no documentation on how exactly these text suggestions work programmatic-wise. This is a reverse engineering conclusion.

There are no guarantees next time they won't use an empty string instead of a single space, there are no guarantees they won't introduce a single-step process in iOS 13 or even a real callback or something.

You see, there's a similar problem #32. And the only somewhat reliable solution (#33) affects the main dispatch queue, hence affects the main run loop. Hence, affects all the view controller transitions, for instance. And many other things relying on the main queue consecutive consistency.

All because in iOS 11 they've decided to asynchronously recalculate cursor positioning for some reason. A completely legitimate step since there's no documentation on how the text is pasted from the clipboard programmatic-wise.
