### ISSUE TITLE
Multiple masked text fields

### ISSUE THREAD

**Issue by LinusGeffarth** [RedMadRobot/input-mask-ios#55]
First off, awesome library. Easy to use and works really well :) 👍

Now, am I right, that, if I wanted to implement multiple masked text fields, I'd have to add a `MaskedTextFieldDelegate` object for each one?

**Comment by taflanidi** [comment]
Hey @LinusGeffarth!
Thanks for your kind words.

Answering your question, it depends on what kind of data you have in your text fields.

If you have, like, several fields with phone numbers — you may incorporate a single `MaskedTextFieldDelegate` object for all of them since the masks are going to be the same.

**Comment by LinusGeffarth** [comment]
Okay so one delegate object for each mask.

**Comment by taflanidi** [comment]
> why didn't you implement it so that the mask is a property of the text field and all text fields share the same delegate?

@LinusGeffarth, I would not call this a wise design decision.

Custom text field would interfere with other custom text fields and overall inheritance hierarchy. You won't be able to use masking with other library's custom text fields; or otherwise, you'll end up with all your text fields having a mask property, which contradicts common sense. The same story would occur with your `UITextView`s, and that's even a bigger bummer.

Using an Occam's razor, the only thing our library operates over is text alterations. From this point of view, the best way to implement its functionality is to hook up to the `on text changed` callback, as it was done for the Android counterpart.

The closest thing to it is a stupid ass `UITextFieldDelegate` protocol and the `delegate` property; `onEditingChanged` events are deferred, async and unreliable, plus there's no such thing as target-action relationship for the `UITextView` objects.

Thus, it's the most optimal way with the smallest amount of synthetic entities and the smallest impact on the user's project.

iOS and macOS SDKs are already poorly designed, let's not complicate life for our colleague developers. (-:

Should you have any related questions, please ask them right away; otherwise please close this thread.

**Comment by LinusGeffarth** [comment]
Makes sense, thanks for the elaboration!
