### ISSUE TITLE
Waiting for discussion

### ISSUE THREAD

**Issue by obj-dayao** [RedMadRobot/input-mask-ios#79]
Prerequisites
done.

Summary
My mask is [099999]{.}[00]，When entering the sixth place, I don’t think it should bring the decimal point directly, but the seventh place. e.g. When I just need a 6-digit integer, I have to delete the decimal point.

**Comment by taflanidi** [comment]
Hey @obj-dayao!
Thanks for your question.

In the prerequisites section — which you have conveniently omitted — there's a requirement for you to read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki).

According to our Wiki, there's an [autocompletion feature](https://github.com/RedMadRobot/input-mask-ios/wiki/0.-Mask#autocomplete-flag) provided with two examples demonstrating the exact behaviour you are talking about. In order to turn autocompletion off, the Wiki states, there's a dedicated [text field listener](https://github.com/RedMadRobot/input-mask-ios/wiki/2.-Text-Field-Listener) `@IBInspectable` property called [autocomplete](https://github.com/RedMadRobot/input-mask-ios/wiki/2.-Text-Field-Listener#properties), which you may also assign during the [initialisation](https://github.com/RedMadRobot/input-mask-ios/wiki/2.-Text-Field-Listener#initialisation).

The property equals `true` by default, though you may alter it on the fly.

**Comment by obj-dayao** [comment]
I had found it. Thank you
