### ISSUE TITLE
Is any way to get original string ?

### ISSUE THREAD

**Issue by TikhonovAlexander** [RedMadRobot/input-mask-ios#9]
Hi, thanks for good library!

I have an issue, let's say,  I have a text field with format "{+7} ([000]) [000] [0000]" and property textfield.text gives me "+7 (937) 444 3333", so it's ok for ui, but I need original string for making request to server, is it possible to get original input text "79374443333" ?

**Comment by taflanidi** [comment]
Hey @TikhonovAlexander 
Thanks for your question.

First of all, you should have received a callback from the `MaskedTextFieldDelegateListener` (a property of `MaskedTextFieldDelegate`) with the extracted `value` in it on user input.
Second, every `MaskedTextFieldDelegate` has its associated `Mask` instance open for your needs. Thus, you may call 
```
let text = CaretString(string: textfield.text, caretPosition: textfield.text.endIndex)
let extractedValue = maskedTextFieldDelegate.mask.apply(toText: text, autocomplete: ...). extractedValue
```
in order to get the `value` again.

Should you have any questions, please go ahead and ask them.

**Comment by TikhonovAlexander** [comment]
Oh now, it's clear. Thank you !

**Comment by cubixlabs** [comment]
I am able to do masking but now after successful masking I want to do it reverse mask so that I may send plan text to server. for example if a user enters: (56)-55 (for mask formate ([11])-[11]), I want to make it plan text like 5665 and use it.


Please note that extractedValue is not returning plan text (unmasked text) if it is an issue then, it should be resolved.

**Comment by alierdogan7** [comment]
> Hey @TikhonovAlexander Thanks for your question.
> 
> First of all, you should have received a callback from the `MaskedTextFieldDelegateListener` (a property of `MaskedTextFieldDelegate`) with the extracted `value` in it on user input.
> 
> Second, every `MaskedTextFieldDelegate` has its associated `Mask` instance open for your needs. Thus, you may call
> 
> ```swift
> let text = CaretString(string: textfield.text, caretPosition: textfield.text.endIndex)
> let extractedValue = 
>     maskedTextFieldDelegate.mask.apply(toText: text, autocomplete: ...).extractedValue
> ```
> 
> in order to get the `value` again.
> 
> Should you have any questions, please go ahead and ask them.

Thanks for explanation. Could you add this to wiki page in order for other people to find out easily?
